config/routes.rb
Rails.application.routes.draw do
  resources :connectors
  resources :logs

  root 'connectors#index'
  post '/inbound', to: 'connectors#inbound'

end

app/models/connector.rb
class Connector < ActiveRecord::Base
	validates :mug_number, uniqueness: true, presence: true
	validates :channel, uniqueness: true, presence: true
	validates_format_of :user_number, :with => /[+]+[1]+\d{10}/, :allow_blank => true

	after_save :announce_user_number_change

	def channel_name
    	client = Slack::Web::Client.new
    	return client.channels_info(channel: self.channel)['channel']['name']
	end

	def announce_user_number_change
    	client = Slack::Web::Client.new
    	client.chat_postMessage text: "I now send messages in this channel to " + self.user_number, channel: self.channel, as_user: true if self.user_number_changed?
	end
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "ideation" && password == "cocreation"
    end
  end
end

app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  before_action :set_connector, only: [:show, :edit, :update, :destroy]
  before_action :set_numbers_and_channels, except: [:show, :index, :inbound]
  before_filter :authenticate, :except => :inbound
  protect_from_forgery :except => :inbound

  # GET /connectors
  # GET /connectors.json
  def index
    @connectors = Connector.all
  end

  # GET /connectors/1
  # GET /connectors/1.json
  def show
  end

  # GET /connectors/new
  def new
    @connector = Connector.new
  end

  # GET /connectors/1/edit
  def edit
  end

  # POST /connectors
  # POST /connectors.json
  def create
    @connector = Connector.new(connector_params)

    respond_to do |format|
      if @connector.save
        format.html { redirect_to @connector, notice: 'Connector was successfully created.' }
        format.json { render :show, status: :created, location: @connector }
      else
        format.html { render :new }
        format.json { render json: @connector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connectors/1
  # PATCH/PUT /connectors/1.json
  def update
    respond_to do |format|
      if @connector.update(connector_params)
        format.html { redirect_to @connector, notice: 'Connector was successfully updated.' }
        format.json { render :show, status: :ok, location: @connector }
      else
        format.html { render :edit }
        format.json { render json: @connector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connectors/1
  # DELETE /connectors/1.json
  def destroy
    @connector.destroy
    respond_to do |format|
      format.html { redirect_to connectors_url, notice: 'Connector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /inbound
  def inbound
    Log.create(title: "Inbound message received.", raw_data: params.to_json)
    @connector = Connector.find_by(mug_number: params['To'])
    @connector.update_attribute(:user_number, params['From'])

    client = Slack::Web::Client.new
    message = "Message from " + params['From'] + ": " + params['Body']
    message += " (Attachment: " + params['MediaUrl0'] + ")" if params['MediaUrl0']
    client.chat_postMessage text: message, channel: @connector.channel, as_user: true

    render status: 200, text: ''
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connector
      @connector = Connector.find(params[:id])
    end

    def set_numbers_and_channels
      client = Slack::Web::Client.new
      @channels = client.channels_list['channels'].select {|channel| channel['is_member'] }.map {|channel| [channel['name'], channel['id']] }
      @numbers = TwilioClient.incoming_phone_numbers.list().map { |number| number.phone_number }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connector_params
      params.require(:connector).permit(:channel, :mug_number, :user_number)
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.order('created_at DESC')
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

=begin
  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:title, :raw_data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connectors_helper.rb
module ConnectorsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/connectors/_form.html.erb
<%= form_for(@connector) do |f| %>
  <% if @connector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connector.errors.count, "error") %> prohibited this connector from being saved:</h2>

      <ul>
      <% @connector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :channel %><br>
    <%= f.select :channel, options_for_select(@channels, :selected => f.object.channel) %>
  </div>
  <div class="field">
    <%= f.label :mug_number %><br>
    <%= f.select :mug_number, options_for_select(@numbers, :selected => f.object.mug_number) %>
  </div>
  <div class="field">
    <%= f.label :user_number %><br>
    <%= f.text_field :user_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connectors/edit.html.erb
<h1>Editing Connector</h1>

<%= render 'form' %>

<%= link_to 'Show', @connector %> |
<%= link_to 'Back', connectors_path %>

app/views/connectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Connectors</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Mug number</th>
      <th>User number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @connectors.each do |connector| %>
      <tr>
        <td><%= connector.channel_name %></td>
        <td><%= connector.mug_number %></td>
        <td><%= connector.user_number %></td>
        <td><%= link_to 'Show', connector %></td>
        <td><%= link_to 'Edit', edit_connector_path(connector) %></td>
        <td><%= link_to 'Destroy', connector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connector', new_connector_path %>

app/views/connectors/new.html.erb
<h1>New Connector</h1>

<%= render 'form' %>

<%= link_to 'Back', connectors_path %>

app/views/connectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @connector.channel_name %>
</p>

<p>
  <strong>Mug number:</strong>
  <%= @connector.mug_number %>
</p>

<p>
  <strong>User number:</strong>
  <%= @connector.user_number %>
</p>

<%= link_to 'Edit', edit_connector_path(@connector) %> |
<%= link_to 'Back', connectors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turingmugs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
Turing Mugs
<nav>
<%= link_to "Connectors", controller: 'connectors' %>
<%= link_to "Logs", controller: 'logs' %>
</nav>
</header>

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :raw_data %><br>
    <%= f.text_field :raw_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Raw data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.title %></td>
        <td><%= log.raw_data %></td>
        <td><%= log.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @log.title %>
</p>

<p>
  <strong>Raw data:</strong>
  <%= @log.raw_data %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>